exports.diwali = [
  "All of the lamps and all of the fireworks will brighten every step forward for you this Diwali!",
  "For every light you see this year, may the blessings of Diwali shine even brighter for you.",
  "Here’s to every joy and blessing this Diwali!",
  "May God bring all the happiness and beauty to your life this Diwali.",
  "Blessings from the Supreme Light of Lights is upon you!",
  "Happy Diwali! May blessings of wealth and beauty abound to you!",
  "For this auspicious festival of lights, here’s to the warmth of joy illuminating your days!",
  "Wishing you and your family a very Happy Diwali.",
  "Your family has been so great to me – I wish you all the best for Diwali this year!",
  "For this Diwali, I am hoping you are blessed with all the showers of wealth and joy!",
  "The light of Goodness and Prosperity will be bright for you this year. Happy Diwali!",
  "Now and always, may you and your close ones have the most prosperous and wonderful days!",
  "We are so blessed to have friends and family like you – Happy Diwali!",
  "As Diwali comes upon you, remember to make the most of every opportunity!",
  "Bring joy and prosperity to every smile you share this Diwali.",
];
exports.hanukkah = [
  "Best Wishes for a Wonderful Holiday Season and a New Year filled with Peace and Happiness.",
  "Family and Friends are a wonderful part of Hanukkah!",
  "May all the joys of Hanukkah fill your heart throughout the New Year.",
  "May Hanukkah bring you Joy and the New Year every Blessing.",
  "May Joy and Peace be yours throughout the New Year.",
  "May the many gifts of this blessed season be yours.",
  "May the Peace and Joy of the Holiday Season be with you throughout the coming year.",
  "May the Spirit of Hanukkah be with you throughout the New Year.",
  "May this Joyous Season bring you peace, health and happiness throughout the coming year.",
  "May you have the spirit of Hanukkah which is Peace, the gladness of Hanukkah which is Hope, and the Heart of Hanukkah which is Love.",
  "Season’s Greetings and Best Wishes for the New Year.",
  "The Gift of Hanukkah is a precious reminder that we are loved!",
  "The gift of love, the gift of peace The gift of happiness… May these be yours at Hanukkah.",
  "The Magic of Hanukkah never ends and its greatest of gifts are family and friends. Happy Hanukkah and Happy New Year!",
  "Warmest greetings of the Season and best wishes for Happiness in the New Year with Hanukkah Blessings.",
  "Warmest Wishes for a Happy Hanukkah and a Happy New Year.",
  "Warmest Wishes of the season from our family to yours.",
  "Wishing you a beautiful holiday and a New Year of peace and happiness.",
  "Wishing you a Hanukkah overflowing with Love and Laughter! ",
  "Wishing you a joyous Holiday Season and a smashing New Year.",
  "Wishing you every happiness this Holiday Season and throughout the coming year!",
  "Wishing you Joy and Peace during Hanukkah and throughout the New Year.",
  "Wishing you peace, love and laughter this Holiday Season and throughout the coming year.",
  "With all Best Wishes for a Joyous Season and a very Happy New Year.",
  "With every wish for a very Happy Hanukkah and the Happiest of New Years.",
];
exports.christmas = [
  "Tis the season to wish one another joy and love and peace. Merry Christmas.",
  "Holiday time and all the time, I so appreciate the great work you do.",
  "Happy Holidays and all the best to you in the year to come.",
  "Good tidings we bear to you and your family! May we all have a Merry Christmas.",
  "May God bless you with a festive, loving and peaceful celebration this Christmas and all throughout the year.",
  "Praying you have a wonderful Christmas filled with moments you’ll always remember.",
  "I wish you the unconditional love of God in all the dreams of your heart and your everyday prayers. Merry Christmas.",
  "A silent night, a star above, a blessed gift of hope and love. A Merry Christmas to you and your whole family.",
  "May your world be filled with warmth and good cheer this Holy season, we wish you a joy-filled Christmas.",
  "May the joy and peace of Christmas be with you all through the New Year. Wishing you a season of blessings from heaven above.",
  "May your Christmas be filled with the true miracles and meaning of this Merry time.",
  "Here’s to a year of blessings and beyond. Have a Merry Christmas!",
  "May Santa Claus bring everything you wished for. Merry Christmas!",
  "The gift of love. The gift of peace. The gift of happiness. May all these be yours at Christmas.",
  "Wishing you a very Merry Christmas.",
  "Merry Christmas and a Happy New Year!",
];
